### TODO:
    remove b_draw r_draw columns since all values are null, edit comments

In [59]:
import sys
del sys.modules['mainModel']


In [60]:
import import_ipynb
import mainData
import mainModel

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_selection import VarianceThreshold

importing Jupyter notebook from mainModel.ipynb
5
current number is:  3
x is:  9


In [61]:
# gets clean df with categorical data, 3215 x 140 columns, where only B_draw and R_draw is NaN
data = mainData.getCleanDF()

In [62]:
X = data.drop(['B_draw', 'R_draw', 'Winner'], axis=1)
y = data["Winner"]
toPredict = X.head(15)

In [63]:
model2 = mainModel.modelManager2(X, y, toPredict)
predict = model2.getPrediction()


91


In [64]:
predict

{'decisionTree': {'model': DecisionTreeClassifier(),
  'accuracy': 0.536547433903577,
  'prediction': array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0], dtype=int64),
  'recall': 0.3368030629337162},
 'naiveBayes': {'model': GaussianNB(),
  'accuracy': 0.49300155520995337,
  'prediction': array([0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1], dtype=int64),
  'recall': 0.3386892445420379},
 'randomForest': {'model': RandomForestClassifier(),
  'accuracy': 0.6220839813374806,
  'prediction': array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0], dtype=int64),
  'recall': 0.35752994665202764},
 'svm': {'model': SVC(gamma='auto'),
  'accuracy': 0.6189735614307932,
  'prediction': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
  'recall': 0.3333333333333333},
 'KNN': {'model': KNeighborsClassifier(n_neighbors=91),
  'accuracy': 0.6174183514774495,
  'prediction': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
  'recall': 0.33362189096744227}}

In [65]:
#data.head(15)
recall = 0
acc = 0
for i in predict.keys():
    recall += predict[i]["recall"]
    acc += predict[i]["accuracy"]

recall /= len(predict)
acc /= len(predict)
print(recall,acc)

0.33999549568571147 0.5776049766718507


In [104]:
predDT = predict["randomForest"]["prediction"]
realY = y.head(15)
print(predDT.shape, y.head(15).shape)

(15,) (15,)


In [105]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(realY, predDT)
print(cm)

[[7 0]
 [0 8]]


In [110]:
for i in predict.keys():
    print(confusion_matrix(y.head(15), predict[i]["prediction"]), end="\n\n")

[[6 1]
 [1 7]]

[[3 3 1]
 [0 7 1]
 [0 0 0]]

[[7 0]
 [0 8]]

[[7 0]
 [8 0]]



# TODO:
ROC AOC curve